---
# elixir-release/defaults/main.yml

# A unique prefix for our directories
# This could be your organization or the overall project
elixir_release_org: myorg

# The external name of the app, used to name directories and the systemd unit
elixir_release_name: foo

# The internal "Elixir" name of the app, used to by Distillery to name
# directories and scripts

elixir_release_name_code: "{{ elixir_release_name }}"

# Version of the app in the release
# Default is to read from file
# elixir_release_version: "0.1.0"

# App environment
elixir_release_mix_env: prod

# HTTP listen port
elixir_release_http_listen_port: 4001

# OS user that deploys / owns the release files
elixir_release_deploy_user: deploy
# OS group that deploys / owns the release files
elixir_release_deploy_group: "{{ elixir_release_deploy_user }}"

# OS user that the app runs under
elixir_release_app_user: "{{ elixir_release_name }}"
# OS group that the app runs under
elixir_release_app_group: "{{ elixir_release_app_user }}"

# Base directory for deploy files
elixir_release_deploy_dir: /opt/{{ elixir_release_org }}/{{ elixir_release_name }}
elixir_release_releases_dir: "{{ elixir_release_deploy_dir }}/releases"

# Location for app temp files
elixir_release_temp_dir: /var/tmp/{{ elixir_release_org }}/{{ elixir_release_name }}

# These dirs are only created if they are defined
# Location of per-machine config files
# elixir_release_conf_dir: /etc/{{ elixir_release_name }}

# Location of runtime scripts, e.g. used in cron jobs
# elixir_release_scripts_dir: "{{ elixir_release_deploy_dir }}/scripts"

# Location of runtime logs
# elixir_release_log_dir: /var/log/{{ elixir_release_name }}

# Base directory for app data
# elixir_release_var_dir: /var/{{ elixir_release_org }}/{{ elixir_release_name }}

# Location of app data files
# elixir_release_data_dir: "{{ elixir_release_var_dir }}/data"

# Path to conform conf file
# elixir_release_conform_conf_path: "{{ elixir_release_conf_dir }}/{{ elixir_release_name_code }}.conf"

# Location of flag dir
elixir_release_shutdown_flag_dir: "/var/tmp/{{ elixir_release_deploy_user }}/{{ elixir_release_name }}"
elixir_release_shutdown_flag_file: "{{ app_shutdown_flag_dir }}/shutdown.flag"

elixir_release_restart_method: systemctl
# elixir_release_restart_method: touch

# Defaults
# Open file limits
elixir_release_limit_nofile: 65536
# Seconds to wait between restarts
elixir_release_systemd_restart_sec: 5
